### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by farazBhatti** [BMW-InnovationLab/BMW-YOLOv3-Training-Automation#2]
getting above mentioned error after executing this line 
`sudo docker build -f docker/Dockerfile -t darknet_yolo_gpu:1 --build-arg GPU=1 --build-arg CUDNN=1 --build-arg CUDNN_HALF=0 --build-arg OPENCV=1 --build-arg DOWNLOAD_ALL=1 .
`
Any ideas? Ive gone through few solutions given online but no result

**Comment by nok** [comment]
Did you try to restart the Docker daemon with `sudo service docker restart`?
And which operating system are you using and how did you install Docker on the host machine?

**Comment by manishalankala** [comment]
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.


it didnot work

**Comment by roy6324** [comment]
Hello @farazBhatti , 

Please run " systemctl status docker " and check if docker is running. 
If it's not active, then try running " systemctl start docker" to see if it works.
If it's active, use " systemctl stop docker " and then " sudo dockerd " to start the daemon manually.

If the issue remains, please provide the output of " docker info ".

**Comment by nourazzii** [comment]
Hello @farazBhatti 
Please follow the instructions in https://docs.docker.com/get-started/ for a clean docker installation.
We will close this issue as it is not related to our project.
