### ISSUE TITLE
More than 10k iterations possible?

### ISSUE THREAD

**Issue by AGrosserHH** [BMW-InnovationLab/BMW-YOLOv3-Training-Automation#5]
Hi all,

I am trying to run a classifier with 20 object types and some 100k images as training data. I tried it three times and each time it stops at step 10k and does not continue any more.
In the log file it says

     (next mAP calculation at 10300 iterations) 
     Last accuracy mAP@0.5 = 10.97 %, best = 11.05 % 
    10115: 0.903671, 0.621472 avg loss, 0.001000 rate, 4.427342 seconds, 323680 images
    MJPEG-stream sent. 
    Loaded: 0.000051 seconds

It does not continue anymore. Do I need to set something in the model?

Cheers,
Andi

**Comment by nourazzii** [comment]
Hello Andi,
Can you please provide any additional information on the dataset?
And it would help if you can share your config file in the reply
