### ISSUE TITLE
No such file or directory: '../training/config/darknet/yolo_default_weights/yolov3.weights'

### ISSUE THREAD

**Issue by KiriUbu** [BMW-InnovationLab/BMW-YOLOv3-Training-Automation#6]
Hello I have a problem when the Training starts.
![1](https://user-images.githubusercontent.com/47858105/75155986-6cd23f00-5711-11ea-9196-9d626ef3bf58.png)

i renamed the Folder to "training" i also downloaded the yolov3 weights again the file exist but the Error is still there. 

![2](https://user-images.githubusercontent.com/47858105/75156131-bb7fd900-5711-11ea-87e9-a26e4711555c.png)

thank you for every help.

**Comment by KiriUbu** [comment]
When running the run_docker_linux_cpu.sh there problem does not appear

**Comment by nourazzii** [comment]
Hello @KiriUbu 
It appears you have created an additional folder "yolov3" 
Can you please move the .weights files to "yolo_default_weights" and report back?
